<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<script>
    //Promise的状态一旦改变，就永久保持该状态，不会再变了
    //Promise在resolve语句后面，再抛出错误。不会被捕获，等于没有抛出。
    const promise = new Promise(function(resolve,reject){
        resolve("ok"); //状态已经变为了resolved的，所以不会再更改状态啦。
        throw new Error("test");
    })

    promise
        .then(val => console.log(val))
        .catch(err => console.log(err));
    //输出： ok

    //若没使用catch方法指定错误处理的回调函数，Promise对象抛出的错误不会传递到外层代码，即不会有任何反应
    const someAsyncThing = function(){
        return new Promise(function(resolve,reject){
            //代码报错，因为x没有声明
            resolve(x+2);
        });
    };

    someAsyncThing().then(function(){
        console.log('everything is great');
    });

    setTimeout(() => console.log(123),2000);
    //Uncaught(in promise) : x is not defined。
    //123   ==> 123还是能被正常输出。


    //Promise.all:将多个Promise实例，包装成一个新的Promise实例。
    /*
    *   Promise.all方法接受一个数组作为参数，p1、p2、p3都是Promise实例；
    *   若不是，就会先调用Promise.resolve方法将参数转化为Promise实例。
    *   p的状态由p1、p2、p3决定，分为两种情况：
    *   （1）只有p1、p2、p3的状态都变成fulfilled，p的状态才会变成fulfilled，此时p1、p2、p3的返回值组成一个数组，传递给p的回调函数。
    *   （2）只要p1、p2、p3之中有一个被rejected，p的状态就变成rejected，此时第一个被reject的实例的返回值，会传递给p的回调函数。
    */
    const p = Promise.all([p1,p2,p3]);

    //Promise.race:将多个Promise实例，包装成一个新的Promise实例。
    //只要p1、p2、p3之中有一个实例率先改变状态，p的状态就跟着改变。那个率先改变的Promise实例的返回值，就传递给p的回调函数。
    const p1 = Promise.race([p1,p2,p3]);

    //5秒之内fetch方法无法返回结果，变量p的状态就会变成rejected，从而触发catch方法指定的回调函数。
    const p = Promise.race([
        fetch('/resource-that-may-take-a-while'),
        new Promise(function(resolve,reject){
            setTimeout(() => reject(new Error("request timeout")),5000)
        })
    ]);

    p
        .then(console.log)
        .catch(console.error);
</script>
</body>
</html>